### ISSUE TITLE
Stop working

### ISSUE THREAD

**Issue by Undercore90** [dumbasPL/aero2solver#1]
Hi,

Can you check if something has changed. It stopped entering the code. The container used to go all the time and since the last update it worked without any problem. When I manually connect to WiFi the page asking me to enter the code opens automatically and after entering the code the internet comes back and the container has a message that internet access granted.

When I get there I will send a screenshot of how the application works. Also, if you write what logs help you I can collect them.

Thanks in advance for your help.

**Comment by dumbasPL** [comment]
From what I can see nothing has changed and still works for me, this is how the log should look like when it solves a captcha:
```
[...]
Captcha not required with message: Dostęp do Internetu został odblokowany.
Captcha not required with message: Dostęp do Internetu został odblokowany.
Captcha not required with message: Dostęp do Internetu został odblokowany.
Captcha not required with message: Dostęp do Internetu został odblokowany.
Captcha required
Trying to solve captcha (try 1)
Captcha solved as biqy8jdv after 1
Captcha solved with message: Odpowiedź prawidłowa. Za 10 sekund dostęp do internetu zostanie odblokowanySprawdź specjalną ofertę dla Ciebie
Sleeping for 60 seconds
Captcha not required with message: Dostęp do Internetu został odblokowany.
Captcha not required with message: Dostęp do Internetu został odblokowany.
Captcha not required with message: Dostęp do Internetu został odblokowany.
[...]
```

**Comment by mariuszste** [comment]
> Do you have any verified DNS that you use and are trouble free with aero?

I just use the one provided by aero. I have the card in a huawei usb modem and I just point the dns at the ip of the modem. Not sure what the actual dns ip is for aero but you can probably figure it out if you put the card in your phone and dig through settings.

**Comment by Undercore90** [comment]
Thanks for your help and your project in general. It is very useful for monitoring devices :). You can close have a nice day :)
