### ISSUE TITLE
Automatic captcha image generation

### ISSUE THREAD

**Issue by og1en** [dumbasPL/aero2solver#4]
https://github.com/aero2a/kape-
kolejne dane
można sobie wygenerować dowolną ilość bo to skrypt php

**Comment by dumbasPL** [comment]
> można sobie wygenerować dowolną ilość bo to skrypt php

wiesz może gdzie mogę ten skrypt znaleźć, bo w podlinkowanym repo są tylko obrazki

**Comment by dumbasPL** [comment]
@og1en bump, closing if no response

**Comment by mix127** [comment]
> wiesz może gdzie mogę ten skrypt znaleźć, bo w podlinkowanym repo są tylko obrazki

Bo to są ręczne dane

**Comment by dumbasPL** [comment]
to useless
